Repository ainblockchain/ain-blockchain, pull requests merged in 2021-06, with the labels that each got.

#424 Add sanitization logic (isValidRuleTree(), isValidRuleConfig()) for rule tree
  db/index.js
  db/state-util.js
  unittest/db.test.js
  unittest/state-util.test.js
Labels: new feature

#425 Version up to 0.7.6
  client/protocol_versions.json
  package.json
Labels: release

#426 Bugfix/unittest issue 419 fix
  unittest/p2p.test.js
Labels: bug

#427 Merge Release/v0.7.6 into develop
  client/protocol_versions.json
  package.json
  unittest/p2p.test.js
  yarn.lock
Labels: release

#428 Merge Release/v0.7.6 into master
  README.md
  client/index.js
  client/protocol_versions.json
  common/constants.js
  common/network-util.js
  common/path-util.js
  common/version-util.js
  consensus/index.js
  db/functions.js
  db/index.js
  db/rule-util.js
  db/state-util.js
  deploy_blockchain_gcp.sh
  deploy_blockchain_incremental_gcp.sh
  deploy_monitoring_gcp.sh
  genesis-configs/base/genesis_owners.json
  integration/afan_dapp.test.js
  integration/blockchain.test.js
  integration/node.test.js
  integration/sharding.test.js
  p2p/index.js
  p2p/server.js
  p2p/util.js
  package.json
  reset_blockchain_gcp.sh
  setup_node_gcp.sh
  setup_tracker_gcp.sh
  start_node_gcp.sh
  start_node_incremental_gcp.sh
  start_servers.sh
  start_servers_afan.sh
  stop_servers.sh
  tools/util.js
  tx-pool/index.js
  unittest/db.test.js
  unittest/functions.test.js
  unittest/p2p-util.test.js
  unittest/p2p.test.js
  unittest/rule-util.test.js
  unittest/state-util.test.js
  yarn.lock
Labels: release

#429 Apply partial set (applyOwnerChange()) in setOwner()
  db/index.js
  db/state-util.js
  unittest/db.test.js
  unittest/state-util.test.js
Labels: new feature

#433 Add service/app name validation and service type validation logic
  blockchain/block.js
  common/chain-util.js
  common/constants.js
  db/functions.js
  db/rule-util.js
  db/state-util.js
  integration/node.test.js
  unittest/rule-util.test.js
  unittest/state-util.test.js
Labels: new feature

#437 Define and apply state label length limit (STATE_LABEL_LENGTH_LIMIT)
  db/state-util.js
  genesis-configs/afan-shard/genesis_params.json
  genesis-configs/base/genesis_params.json
  genesis-configs/sim-shard/genesis_params.json
  genesis-configs/testnet/genesis_params.json
  unittest/state-util.test.js
Labels: new feature

#445 Bugfix/platfowner/bugfix
  .gitignore
  genesis-configs/afan-shard/genesis_params.json
  genesis-configs/base/genesis_params.json
  genesis-configs/sim-shard/genesis_params.json
  genesis-configs/testnet/genesis_params.json
  integration/node.test.js
Labels: enhancement

#446 Merge Release/v0.7.7 into master
  .gitignore
  blockchain/block-file-util.js
  blockchain/block.js
  blockchain/index.js
  client/index.js
  client/protocol_versions.json
  common/chain-util.js
  common/constants.js
  common/file-util.js
  db/functions.js
  db/index.js
  db/rule-util.js
  db/state-util.js
  genesis-configs/afan-shard/genesis_params.json
  genesis-configs/base/genesis_params.json
  genesis-configs/base/genesis_rules.json
  genesis-configs/sim-shard/genesis_params.json
  genesis-configs/testnet/genesis_params.json
  integration/node.test.js
  json_rpc/index.js
  node/index.js
  p2p/index.js
  p2p/server.js
  p2p/util.js
  package.json
  start_node_incremental_gcp.sh
  start_servers.sh
  tx-pool/transaction.js
  unittest/blockchain.test.js
  unittest/chain-util.test.js
  unittest/db.test.js
  unittest/p2p.test.js
  unittest/rule-util.test.js
  unittest/state-util.test.js
  unittest/transaction.test.js
  yarn.lock
Labels: release

#447 Merge release/v0.7.7 into develop
  client/protocol_versions.json
  package.json
Labels: release

#449 Test PR for actions fix
  .github/workflows/github-actions.yml
  integration/afan_dapp.test.js
Labels: bug

#453 Clean up state-related terms
  client/index.js
  common/constants.js
  consensus/constants.js
  consensus/index.js
  integration/sharding.test.js
  json_rpc/index.js
  p2p/index.js
  p2p/server.js
  start_node_incremental_gcp.sh
  tx-pool/index.js
  unittest/p2p.test.js
Labels: enhancement

#455 Rename: ChainUtil -> CommonUtil.
  blockchain/block.js
  client/index.js
  common/common-util.js
  common/constants.js
  common/file-util.js
  common/network-util.js
  common/path-util.js
  consensus/block-pool.js
  consensus/index.js
  db/functions.js
  db/index.js
  db/state-node.js
  db/state-util.js
  integration/afan_dapp.test.js
  integration/blockchain.test.js
  integration/node.test.js
  integration/sharding.test.js
  json_rpc/index.js
  node/index.js
  p2p/index.js
  p2p/server.js
  p2p/util.js
  package.json
  tools/cross-shard/sendCheckinTx.js
  tools/simple-load-test/index.js
  tools/util.js
  tracker-server/index.js
  tx-pool/index.js
  tx-pool/transaction.js
  unittest/chain-util.test.js
  unittest/db.test.js
  unittest/functions.test.js
  unittest/state-node.test.js
  unittest/test-util.js
  unittest/transaction.test.js
  unittest/tx-pool.test.js
Labels: enhancement

#460 Application version alert
  .github/workflows/github-actions.yml
  package.json
  tools/cicd/deployment.js
  yarn.lock
Labels: enhancement, new feature

#461 Merge Release/v0.8.0 into master
  .github/workflows/github-actions.yml
  README.md
  bitbucket-pipelines.yml
  blockchain/block.js
  client/index.js
  client/protocol_versions.json
  common/common-util.js
  common/constants.js
  common/file-util.js
  common/network-util.js
  common/path-util.js
  consensus/block-pool.js
  consensus/constants.js
  consensus/index.js
  db/functions.js
  db/index.js
  db/state-node.js
  db/state-util.js
  integration/afan_dapp.test.js
  integration/blockchain.test.js
  integration/node.test.js
  integration/sharding.test.js
  json_rpc/index.js
  monitoring/grafana.json
  node/index.js
  p2p/index.js
  p2p/server.js
  p2p/util.js
  package.json
  start_node_incremental_gcp.sh
  tools/cicd/deployment.js
  tools/cross-shard/sendCheckinTx.js
  tools/simple-load-test/index.js
  tools/util.js
  tracker-server/index.js
  tx-pool/index.js
  tx-pool/transaction.js
  unittest/chain-util.test.js
  unittest/db.test.js
  unittest/functions.test.js
  unittest/p2p.test.js
  unittest/state-node.test.js
  unittest/test-util.js
  unittest/transaction.test.js
  unittest/tx-pool.test.js
  yarn.lock
Labels: release

#462 Merge Release/v0.8.0 into develop
  bitbucket-pipelines.yml
  client/protocol_versions.json
  package.json
Labels: release
