Repository ainblockchain/ain-blockchain, pull requests merged in 2021-04, with the labels that each got.

#294 Add backupDb() and restoreDb() for easy rollback.
  blockchain/block.js
  common/constants.js
  consensus/index.js
  db/index.js
  node/index.js
  unittest/db.test.js
Labels: enhancement

#298 Always clone the nodes on the path to the write ref point
  db/index.js
  unittest/db.test.js
Labels: bug

#302 Add APIs for tree height
  blockchain/block.js
  client/index.js
  common/constants.js
  consensus/index.js
  db/index.js
  db/state-manager.js
  db/state-node.js
  db/state-util.js
  integration/node.test.js
  json_rpc/index.js
  p2p/server.js
  unittest/db.test.js
  unittest/state-node.test.js
  unittest/state-util.test.js
Labels: new feature

#317 Always return code of transaction execution
  blockchain/block.js
  client/index.js
  common/chain-util.js
  common/constants.js
  common/path-util.js
  consensus/index.js
  db/functions.js
  db/index.js
  integration/afan_dapp.test.js
  integration/node.test.js
  integration/sharding.test.js
  json_rpc/index.js
  node/index.js
  p2p/server.js
  p2p/util.js
  start_servers.sh
  start_servers_afan.sh
  tools/util.js
  unittest/chain-util.test.js
  unittest/consensus.test.js
  unittest/db.test.js
  unittest/functions.test.js
  unittest/transaction.test.js
Labels: enhancement

#319 Return gas amount in tx result
  client/index.js
  common/chain-util.js
  common/constants.js
  db/functions.js
  db/index.js
  db/rule-util.js
  db/state-node.js
  integration/afan_dapp.test.js
  integration/blockchain.test.js
  integration/node.test.js
  integration/sharding.test.js
  json_rpc/index.js
  loadtest/load_tester.sh
  p2p/server.js
  p2p/util.js
  tracker-server/index.js
  tx-pool/index.js
  unittest/blockchain.test.js
  unittest/chain-util.test.js
  unittest/db.test.js
Labels: new feature

#325 Update grafana config.
  monitoring/grafana.json
Labels: bug

#326 Avoid using deprecated packages
  afan_client/index.js
  afan_client/request_manager.js
  integration/afan_dapp.test.js
  package.json
  yarn.lock
Labels: enhancement

#328 Set batch transaction list size limit
  genesis-configs/afan-shard/genesis_params.json
  genesis-configs/base/genesis_params.json
  genesis-configs/sim-shard/genesis_params.json
  genesis-configs/testnet/genesis_params.json
  integration/node.test.js
  json_rpc/index.js
Labels: new feature

#333 Set ENABLE_DEV_CLIENT_API=true in dev environments
  README.md
  start_servers.sh
  start_servers_afan.sh
Labels: enhancement

#329 Check data compatibility
  client/index.js
  common/constants.js
  common/version-util.js
  p2p/index.js
  p2p/server.js
  p2p/util.js
Labels: enhancement, new feature

#334 Move getAddress func to chain-util
  client/index.js
  common/chain-util.js
  p2p/index.js
  p2p/server.js
  p2p/util.js
  tx-pool/transaction.js
Labels: enhancement

#346 Package version up!
  package.json
Labels: bug

#351 Add nonce / gas_price validity checking logic
  README.md
  client/index.js
  common/chain-util.js
  common/constants.js
  db/index.js
  db/rule-util.js
  node/index.js
  package.json
  start_node_gcp.sh
  start_servers.sh
  start_servers_afan.sh
  tx-pool/transaction.js
  unittest/rule-util.test.js
  unittest/transaction.test.js
Labels: enhancement

#356 Feature/data encapsulation
  common/constants.js
  p2p/index.js
  p2p/server.js
  p2p/util.js
Labels: enhancement

#359 Feature/message timestamp
  common/constants.js
  genesis-configs/afan-shard/genesis_params.json
  genesis-configs/base/genesis_params.json
  genesis-configs/sim-shard/genesis_params.json
  genesis-configs/testnet/genesis_params.json
  p2p/index.js
  p2p/server.js
  p2p/util.js
Labels: enhancement

#361 Some code optimization for gas amount
  common/chain-util.js
  common/constants.js
  db/functions.js
  db/index.js
  integration/node.test.js
  integration/sharding.test.js
  unittest/chain-util.test.js
  unittest/db.test.js
  unittest/functions.test.js
Labels: enhancement

#362 Do not return state gas amount.
  common/chain-util.js
  common/constants.js
  db/functions.js
  db/index.js
  integration/node.test.js
  integration/sharding.test.js
  unittest/chain-util.test.js
  unittest/db.test.js
  unittest/functions.test.js
Labels: enhancement

#366 Add REST function call timeout
  common/constants.js
  db/functions.js
  genesis-configs/afan-shard/genesis_params.json
  genesis-configs/base/genesis_params.json
  genesis-configs/sim-shard/genesis_params.json
  genesis-configs/testnet/genesis_params.json
  tools/chatbot/config_gcp.js
  tools/chatbot/config_local.js
  tools/chatbot/sendCreateAppAndConfigTx.js
  tools/chatbot/sendMessageTx.js
  tools/payments/sendClaimTx.js
  tools/transaction-executor/.gitignore
  tools/transaction-executor/bin/run
  tools/transaction-executor/bin/run.cmd
  tools/transaction-executor/chatbot_transactions.json
  tools/transaction-executor/package.json
  tools/transaction-executor/sample_transactions.txt
  tools/transaction-executor/sample_unsigned_transactions.txt
  tools/transaction-executor/src/index.js
Labels: enhancement

#369 Set 0 gas_price for sharding set up tx and shard state proof hash reporting tx
  common/constants.js
  consensus/index.js
  db/index.js
  p2p/server.js
  p2p/util.js
  tools/util.js
Labels: bug

#370 Tweak failed transaction handling logic of tool scripts
  tools/cross-shard/sendCheckinTx.js
  tools/escrow/sendEscrowConfigTx.js
  tools/escrow/sendHoldTx.js
  tools/escrow/sendReleaseTx.js
  tools/payments/sendCreateAppTx.js
  tools/payments/sendPayTx.js
  tools/staking/sendCreateAppTx.js
  tools/staking/sendStakeTx.js
  tools/staking/sendUnstakeTx.js
  tools/transfer/sendTransferTx.js
Labels: enhancement
