Repository ainblockchain/ain-blockchain, pull requests merged in 2021-05, with the labels that each got.

#372 Include function execution results in the transaction results
  common/chain-util.js
  common/constants.js
  db/functions.js
  db/index.js
  integration/node.test.js
  integration/sharding.test.js
  json_rpc/index.js
  package.json
  start_servers.sh
  start_servers_afan.sh
  tx-pool/index.js
  tx-pool/transaction.js
  unittest/chain-util.test.js
  unittest/db.test.js
  unittest/functions.test.js
Labels: enhancement

#374 Update isFailedTx() to check function results as well
  common/chain-util.js
  common/constants.js
  db/functions.js
  integration/afan_dapp.test.js
  integration/blockchain.test.js
  integration/node.test.js
  integration/sharding.test.js
  unittest/chain-util.test.js
  unittest/db.test.js
  unittest/functions.test.js
  unittest/transaction.test.js
Labels: new feature

#386 Use github IDs in TODOs and NOTEs
  README.md
  blockchain/block-file-util.js
  blockchain/block.js
  blockchain/index.js
  common/chain-util.js
  common/constants.js
  consensus/index.js
  db/functions.js
  db/index.js
  integration/blockchain.test.js
  json_rpc/index.js
  node/index.js
  p2p/index.js
  p2p/server.js
  scripts/account_transfer_tester.py
  tools/generateShardGenesisFiles.js
  tracker-server/index.js
Labels: enhancement

#390 Replace JSON.parse() with parseOrLog() for API call responses
  unittest/test-util.js
Labels: enhancement

#393 Fix integration test
  .github/workflows/local/github-actions-for-local.yml
  integration/afan_dapp.test.js
  integration/blockchain.test.js
  integration/node.test.js
  integration/sharding.test.js
  package.json
  unittest/test-util.js
  unittest/transaction.test.js
  unittest/tx-pool.test.js
  yarn.lock
Labels: bug

#396 Turn on/off dev set client API using feature flag ENABLE_DEV_SET_CLIENT_API
  README.md
  blockchain-database.code-workspace
  client/index.js
  common/constants.js
  integration/afan_dapp.test.js
  integration/blockchain.test.js
  integration/node.test.js
  integration/sharding.test.js
  setup_monitoring_gcp.sh
  setup_node_gcp.sh
  start_node_gcp.sh
  start_node_incremental_gcp.sh
  start_servers.sh
  start_servers_afan.sh
  valid_private_keys.txt
Labels: enhancement

#401 Pose limits on the tx pool size and the per-account tx pool size.
  blockchain/block.js
  db/rule-util.js
  genesis-configs/afan-shard/genesis_params.json
  genesis-configs/base/genesis_params.json
  genesis-configs/sim-shard/genesis_params.json
  genesis-configs/testnet/genesis_params.json
  integration/node.test.js
  integration/sharding.test.js
  json_rpc/index.js
  node/index.js
  tx-pool/index.js
  tx-pool/transaction.js
Labels: new feature

#407 Allow function IDs (auth.fid) in owner config
  common/constants.js
  db/functions.js
  db/index.js
  integration/node.test.js
Labels: new feature

#411 Apply owner tree validity checking in setOwner()
  db/functions.js
  db/index.js
  db/rule-util.js
  db/state-util.js
  integration/node.test.js
  integration/sharding.test.js
  p2p/server.js
  package.json
  unittest/db.test.js
  unittest/functions.test.js
  unittest/rule-util.test.js
  unittest/state-util.test.js
Labels: new feature

#415 Do function sanitization logic in setFunction()
  client/index.js
  db/functions.js
  db/index.js
  db/state-util.js
  integration/blockchain.test.js
  integration/node.test.js
  integration/sharding.test.js
  package.json
  unittest/db.test.js
  unittest/state-util.test.js
  yarn.lock
Labels: new feature

#416 Bugfix for p2p test bug
  p2p/index.js
  p2p/server.js
  package.json
  unittest/p2p.test.js
  yarn.lock
Labels: bug

#423 Fix broken sharding test cases.
  common/network-util.js
  p2p/server.js
Labels: bug
