Repository ainblockchain/ain-blockchain, pull requests merged in 2021-09, with the labels that each got.

#551 Apply recursive empty node removal for all parent paths
  db/index.js
  db/state-node.js
  db/state-util.js
  unittest/db.test.js
  unittest/state-node.test.js
  unittest/state-util.test.js
Labels: enhancement

#553 Fix empty label radix bug
  db/radix-node.js
  db/radix-tree.js
  db/state-util.js
  unittest/db.test.js
  unittest/radix-node.test.js
  unittest/radix-tree.test.js
Labels: bug

#555 Turn off enableArrayRadixChildMap and enableHexLabelCache by default
  common/constants.js
  db/radix-child-map.js
  db/radix-node.js
  unittest/db.test.js
  unittest/radix-child-map.test.js
  unittest/radix-node.test.js
  unittest/radix-tree.test.js
  unittest/state-node.test.js
Labels: enhancement

#560 Optimize radix tree related modules
  common/constants.js
  db/index.js
  db/radix-child-map.js
  db/radix-node.js
  db/radix-tree.js
  db/state-node.js
  db/state-util.js
  integration/node.test.js
  package.json
  unittest/db.test.js
  unittest/radix-child-map.test.js
  unittest/radix-node.test.js
  unittest/radix-tree.test.js
  unittest/state-node.test.js
  unittest/state-util.test.js
Labels: bug, enhancement

#561 Add dynamic radix tree, build state info in parallel, tweak computeNodeBytes()
  common/common-util.js
  common/constants.js
  db/radix-node.js
  db/radix-tree.js
  db/state-manager.js
  db/state-node.js
  db/state-util.js
  integration/node.test.js
  unittest/common-util.test.js
  unittest/db.test.js
  unittest/radix-node.test.js
  unittest/radix-tree.test.js
  unittest/state-node.test.js
  unittest/state-util.test.js
  unittest/test-util.js
Labels: enhancement, new feature

#567 Add echo-bot (http://echo-bot.ainetwork.ai) to the function triggering whitelist
  db/functions.js
Labels: enhancement

#563 Feature/minsulee2/network updates for extension
  common/constants.js
  genesis-configs/afan-shard/genesis_params.json
  genesis-configs/base/genesis_params.json
  genesis-configs/he-shard/genesis_params.json
  genesis-configs/sim-shard/genesis_params.json
  genesis-configs/testnet/genesis_params.json
  p2p/index.js
  p2p/server.js
  package.json
  tools/network-topology/README.md
  tools/network-topology/index.html
  tools/network-topology/index.js
  tracker-server/index.js
  unittest/p2p.test.js
  yarn.lock
Labels: new feature

#570 Add traffic manager and /get_client_status client API for traffic stats.
  client/index.js
  common/constants.js
  deploy_blockchain_genesis_gcp.sh
  deploy_blockchain_incremental_gcp.sh
  json_rpc/index.js
  monitoring/grafana.json
  p2p/index.js
  p2p/server.js
  package.json
  restart_tracker_gcp.sh
  start_tracker_incremental_gcp.sh
  tracker-server/index.js
  traffic/event-counter.js
  traffic/traffic-stats-manager.js
  unittest/event-counter.test.js
  unittest/p2p.test.js
  unittest/traffic-stats-manager.test.js
Labels: new feature

#571 Add --setup option to deploy_monitoring_gcp.sh.
  deploy_monitoring_gcp.sh
Labels: enhancement

#572 Fix intervalCount bug in EventCounter.
  traffic/event-counter.js
  unittest/event-counter.test.js
Labels: bug

#575 Optimize radix tree code
  common/constants.js
  db/index.js
  db/radix-node.js
  db/radix-tree.js
  db/state-manager.js
  db/state-node.js
  db/state-util.js
  unittest/db.test.js
  unittest/radix-node.test.js
  unittest/radix-tree.test.js
  unittest/state-node.test.js
  unittest/state-util.test.js
Labels: enhancement

#576 Feature/minsulee2/tracker graph tool integration
  tools/network-topology/README.md
  tracker-server/index.html
  tracker-server/index.js
  tracker-server/network-topology.js
Labels: enhancement

#587 Add missing file
  tracker-server/util.js
Labels: bug
