Repository ainblockchain/ain-blockchain, pull requests merged in 2021-11, with the labels that each got.

#657 Bugfix/liayoo/invalid state proof hash
  db/index.js
  node/index.js
  tools/proof-hash/verifyBlock.js
  unittest/p2p.test.js
Labels: bug

#661 Execute votes in evidence
  consensus/index.js
  integration/sharding.test.js
  node/index.js
  tools/proof-hash/verifyBlock.js
Labels: bug

#659 Update deploy scripts for API nodes
  common/common-util.js
  deploy_blockchain_genesis_gcp.sh
  deploy_blockchain_incremental_gcp.sh
  logger/index.js
  restart_node_gcp.sh
  start_node_genesis_gcp.sh
  start_node_incremental_gcp.sh
Labels: enhancement

#663 Fix lastBlockNumber = -1 for removeOldReceipts when loading blocks.
  blockchain/index.js
  node/index.js
Labels: bug

#665 Fix no 'Invalid state proof hash' error logging bug
  blockchain/block.js
  blockchain/index.js
  client/index.js
  common/common-util.js
  common/constants.js
  common/file-util.js
  common/network-util.js
  consensus/block-pool.js
  consensus/index.js
  db/functions.js
  db/index.js
  db/radix-node.js
  db/radix-tree.js
  db/state-manager.js
  db/state-node.js
  db/state-util.js
  logger/index.js
  node/index.js
  p2p/index.js
  p2p/server.js
  p2p/util.js
  tracker-server/index.js
  tx-pool/index.js
  tx-pool/transaction.js
  unittest/db.test.js
Labels: bug, enhancement

#669 Add full node snapshotting with enableFullNodeSnapshots flag
  client/index.js
  common/common-util.js
  common/constants.js
  db/index.js
  db/radix-node.js
  db/radix-tree.js
  db/state-manager.js
  db/state-node.js
  db/state-util.js
  integration/node.test.js
  node/index.js
  package.json
  restart_node_gcp.sh
  start_node_genesis_gcp.sh
  tools/diff-json/a.json
  tools/diff-json/b.json
  tools/diff-json/jsonDiff.js
  tx-pool/transaction.js
  unittest/common-util.test.js
  unittest/db.test.js
  unittest/radix-node.test.js
  unittest/radix-tree.test.js
  unittest/state-manager.test.js
  unittest/state-node.test.js
  unittest/state-util.test.js
  yarn.lock
Labels: bug, enhancement, new feature

#668 Garbage-collect old receipts per block
  consensus/index.js
  db/index.js
  node/index.js
  tools/proof-hash/verifyBlock.js
  unittest/blockchain.test.js
  unittest/test-util.js
Labels: enhancement

#673 Feature/liayoo/function url wildcard
  common/common-util.js
  common/constants.js
  db/functions.js
  db/index.js
  db/rule-util.js
  db/state-util.js
  integration/function.test.js
  package.json
  unittest/db.test.js
  unittest/functions.test.js
  unittest/rule-util.test.js
  yarn.lock
Labels: enhancement

#674 Add token-level write rule validity checking logic
  common/constants.js
  db/index.js
  db/rule-util.js
  db/state-util.js
  genesis-configs/base/genesis_rules.json
  integration/blockchain.test.js
  integration/he_protocol.test.js
  integration/node.test.js
  integration/sharding.test.js
  package.json
  tools/eval-rule/samples/number.txt
  tools/eval-rule/samples/process_exit.txt
  tools/eval-rule/samples/proposer.txt
  tools/eval-rule/samples/return_true.txt
  tools/eval-rule/samples/transfer.txt
  tools/eval-rule/samples/valid.txt
  tools/eval-rule/tokenizeRule.js
  tools/json-diff/a.json
  tools/json-diff/b.json
  tools/json-diff/jsonDiff.js
  unittest/db.test.js
  unittest/state-util.test.js
  yarn.lock
Labels: new feature

#677 Do not set IP_ADDR_LIST for no account injection options case
  deploy_blockchain_genesis_gcp.sh
Labels: bug

#678 Add ENABLE_JSON_RPC_API and revamp deploy scripts
  README.md
  client/index.js
  common/constants.js
  deploy_blockchain_genesis_gcp.sh
  deploy_blockchain_incremental_gcp.sh
  integration/blockchain.test.js
  integration/consensus.test.js
  integration/dapp.test.js
  integration/function.test.js
  integration/he_protocol.test.js
  integration/he_sharding.test.js
  integration/node.test.js
  integration/sharding.test.js
  json_rpc/index.js
  reset_blockchain_gcp.sh
  restart_node_gcp.sh
  restart_tracker_gcp.sh
  start_node_genesis_gcp.sh
  start_node_incremental_gcp.sh
  start_servers_afan_local.sh
  start_servers_local.sh
  start_tracker_genesis_gcp.sh
  start_tracker_incremental_gcp.sh
Labels: enhancement, new feature

#679 Genesis account revamping with 100 genesis accounts
  blockchain/block.js
  blockchain/index.js
  common/constants.js
  genesis-configs/afan-shard/genesis_accounts.json
  genesis-configs/afan-shard/genesis_params.json
  genesis-configs/base/genesis_accounts.json
  genesis-configs/base/genesis_params.json
  genesis-configs/he-shard/genesis_accounts.json
  genesis-configs/he-shard/genesis_params.json
  genesis-configs/sim-shard/genesis_accounts.json
  genesis-configs/sim-shard/genesis_params.json
  p2p/server.js
  tools/account/generateAccounts.js
  tools/generateAccounts.js
  tools/genesis-file/generateShardGenesisFiles.js
  unittest/db.test.js
  unittest/p2p.test.js
Labels: enhancement

#682 Add punctuator token blacklist for write rules
  db/state-util.js
  integration/node.test.js
  tools/eval-rule/samples/assignment.txt
  unittest/db.test.js
  unittest/state-util.test.js
Labels: enhancement, new feature

#681 Enable/disable JSON RPC transaction APIs with ENABLE_JSON_RPC_TX_API flag
  common/constants.js
  genesis-configs/afan-shard/genesis_params.json
  genesis-configs/base/genesis_params.json
  genesis-configs/he-shard/genesis_params.json
  genesis-configs/sim-shard/genesis_params.json
  genesis-configs/testnet/genesis_params.json
  json_rpc/index.js
  start_node_genesis_gcp.sh
  start_node_incremental_gcp.sh
  unittest/db.test.js
Labels: bug

#686 Add /get_env dev client API for env variables
  client/index.js
  p2p/index.js
  p2p/server.js
  unittest/p2p.test.js
Labels: enhancement

#684 Modularize block validation & execution
  block-pool/index.js
  blockchain/block.js
  blockchain/index.js
  common/constants.js
  common/file-util.js
  consensus/consensus-util.js
  consensus/constants.js
  consensus/index.js
  db/index.js
  deploy_blockchain_genesis_gcp.sh
  deploy_blockchain_incremental_gcp.sh
  integration/function.test.js
  integration/he_protocol.test.js
  node/index.js
  p2p/index.js
  p2p/server.js
  unittest/block-pool.test.js
  unittest/blockchain.test.js
  unittest/p2p.test.js
  unittest/test-util.js
Labels: enhancement

#689 Add block and root_proof_hash to blockchain snapshots
  blockchain/block.js
  blockchain/index.js
  common/constants.js
  consensus/index.js
  db/index.js
  node/index.js
  tools/proof-hash/verifyBlock.js
Labels: enhancement

#694 Add express rate limit config for ddos protection
  client/index.js
  common/constants.js
  deploy_blockchain_genesis_gcp.sh
  deploy_blockchain_incremental_gcp.sh
  deploy_monitoring_gcp.sh
  package.json
  setup_blockchain_ubuntu.sh
  setup_monitoring_gcp.sh
  setup_monitoring_ubuntu.sh
  start_monitoring_gcp.sh
  start_node_genesis_gcp.sh
  start_node_incremental_gcp.sh
  start_servers_afan_local.sh
  start_servers_local.sh
  start_tracker_genesis_gcp.sh
  start_tracker_incremental_gcp.sh
  stop_servers_local.sh
  wait_until_node_sync_gcp.sh
  yarn.lock
Labels: new feature

#706 [bugfix] Set P2P_PEER_CANDIDATE_URL when deploying gcp
  start_node_genesis_gcp.sh
Labels: bug

#704 Improve randomness for proposer selection
  common/constants.js
  consensus/consensus-util.js
  consensus/index.js
  db/rule-util.js
  integration/blockchain.test.js
  integration/consensus.test.js
  integration/dapp.test.js
  integration/function.test.js
  integration/he_protocol.test.js
  integration/he_sharding.test.js
  integration/node.test.js
  integration/sharding.test.js
  unittest/consensus.test.js
Labels: enhancement

#708 Use the json rpc url in response instead of the given api url
  p2p/index.js
  start_node_genesis_gcp.sh
Labels: bug

#710 Fix null state version bug
  common/constants.js
  consensus/index.js
  db/functions.js
  db/index.js
  db/state-manager.js
  db/state-node.js
  db/state-util.js
  node/index.js
  p2p/index.js
  p2p/server.js
  tx-pool/index.js
  unittest/state-node.test.js
Labels: bug, enhancement

#712 Fix broken test case.
  unittest/p2p.test.js
Labels: bug

#716 Fix node module installation errors
  start_node_genesis_gcp.sh
  start_node_incremental_gcp.sh
  start_tracker_genesis_gcp.sh
  start_tracker_incremental_gcp.sh
Labels: bug

#720 Add verifyProofHashForStateTree() util function (with verifyProofHashForRadixTree())
  db/radix-node.js
  db/radix-tree.js
  db/state-util.js
  integration/node.test.js
  node/index.js
  tools/proof-hash/samples/block-101.json.gz
  tools/proof-hash/samples/block-102.json.gz
  tools/proof-hash/samples/block-201.json.gz
  tools/proof-hash/samples/block-202.json.gz
  tools/proof-hash/samples/proof-symbol.json
  tools/proof-hash/samples/proof-test1-manipulated.json
  tools/proof-hash/samples/proof-test1.json
  tools/proof-hash/samples/snapshot-100.json.gz
  tools/proof-hash/samples/snapshot-200.json.gz
  tools/proof-hash/verifyBlock.js
  tools/proof-hash/verifyProof.js
  tools/proof-hash/verifySnapshot.js
  unittest/db.test.js
  unittest/state-util.test.js
Labels: enhancement, new feature

#721 Introduce BlockchainConfigs for flags and constants
  blockchain/index.js
  client/index.js
  common/common-util.js
  common/constants.js
  common/file-util.js
  common/network-util.js
  common/version-util.js
  consensus/consensus-util.js
  consensus/index.js
  db/functions.js
  db/index.js
  db/radix-node.js
  db/rule-util.js
  db/state-node.js
  db/state-util.js
  integration/blockchain.test.js
  integration/consensus.test.js
  integration/dapp.test.js
  integration/function.test.js
  integration/he_protocol.test.js
  integration/he_sharding.test.js
  integration/node.test.js
  integration/sharding.test.js
  json_rpc/index.js
  logger/winston-util.js
  node/index.js
  p2p/index.js
  p2p/server.js
  p2p/util.js
  tools/genesis-file/createGenesisBlock.js
  tools/proposer-stats/getProposerStats.js
  tools/util.js
  tracker-server/index.js
  tx-pool/index.js
  tx-pool/transaction.js
  unittest/block-pool.test.js
  unittest/blockchain.test.js
  unittest/consensus.test.js
  unittest/db.test.js
  unittest/functions.test.js
  unittest/p2p-util.test.js
  unittest/p2p.test.js
  unittest/radix-node.test.js
  unittest/state-util.test.js
  unittest/test-util.js
  unittest/transaction.test.js
  unittest/tx-pool.test.js
Labels: enhancement, new feature

#724 Handle CORS_WHITELIST = * exceptionally
  client/index.js
  start_node_genesis_gcp.sh
  start_node_incremental_gcp.sh
Labels: bug

#722 Fix excessive messaging during restart (+ memory issues).
  consensus/index.js
  integration/he_sharding.test.js
  integration/sharding.test.js
  p2p/index.js
  p2p/server.js
Labels: bug

#726 Support testnet-sandbox env
  blockchain-configs/testnet-sandbox/blockchain_params.json
  blockchain-configs/testnet-sandbox/genesis_block.json.gz
  deploy_blockchain_genesis_gcp.sh
  deploy_blockchain_incremental_gcp.sh
  deploy_monitoring_gcp.sh
  setup_blockchain_ubuntu.sh
  setup_monitoring_ubuntu.sh
  start_node_genesis_gcp.sh
  start_node_incremental_gcp.sh
  start_tracker_genesis_gcp.sh
  start_tracker_incremental_gcp.sh
Labels: new feature

#729 Rename IN_BLOCK tx state to FINALIZED.
  common/constants.js
  integration/consensus.test.js
  integration/he_sharding.test.js
  integration/sharding.test.js
  node/index.js
  tools/verify-tx/sample_tx.json
  tx-pool/index.js
  unittest/test-util.js
Labels: enhancement

#733 Set P2P_PEER_CANDIDATE_URL properly for node restarts
  deploy_blockchain_genesis_gcp.sh
  deploy_blockchain_incremental_gcp.sh
  p2p/index.js
  start_node_genesis_gcp.sh
  start_node_incremental_gcp.sh
  start_tracker_incremental_gcp.sh
Labels: bug, enhancement

#735 Set some flag values true in local scripts
  start_servers_afan_local.sh
  start_servers_local.sh
Labels: bug

#737 Bugfix/liayoo/cannot process vote issue
  README.md
  block-pool/index.js
  blockchain-configs/afan-shard/blockchain_params.json
  blockchain-configs/base/blockchain_params.json
  blockchain-configs/he-shard/blockchain_params.json
  blockchain-configs/sim-shard/blockchain_params.json
  blockchain-configs/testnet-dev/blockchain_params.json
  blockchain-configs/testnet-prod/blockchain_params.json
  blockchain-configs/testnet-sandbox/blockchain_params.json
  blockchain-configs/testnet-staging/blockchain_params.json
  blockchain-configs/unit-tests/blockchain_params.json
  common/constants.js
  consensus/consensus-util.js
  consensus/index.js
  integration/blockchain.test.js
  integration/consensus.test.js
  integration/dapp.test.js
  integration/function.test.js
  integration/he_protocol.test.js
  integration/he_sharding.test.js
  integration/node.test.js
  integration/sharding.test.js
  p2p/index.js
  p2p/server.js
  package.json
  start_node_genesis_gcp.sh
  start_node_incremental_gcp.sh
  start_servers_afan_local.sh
  start_servers_local.sh
Labels: bug

#740 Fix lastBlockNumber fetch in wait_until_node_synced_gcp.sh
  deploy_blockchain_incremental_gcp.sh
  integration/blockchain.test.js
  integration/consensus.test.js
  json_rpc/index.js
  wait_until_node_sync_gcp.sh
Labels: bug

#744 Move gas amount constants to BlockchainConfigs
  common/constants.js
  db/functions.js
  db/index.js
  integration/function.test.js
  unittest/db.test.js
  unittest/functions.test.js
Labels: enhancement
