Repository ainblockchain/ain-blockchain, pull requests merged in 2021-12, with the labels that each got.

#746 Add latency to the traffic stats
  client/index.js
  json_rpc/index.js
  monitoring/grafana.json
  p2p/index.js
  p2p/server.js
  package.json
  traffic/traffic-database.js
  traffic/traffic-stats-manager.js
  unittest/event-counter.test.js
  unittest/p2p.test.js
  unittest/traffic-database.test.js
  unittest/traffic-stats-manager.test.js
Labels: new feature

#750 Merge Release/v0.9.3 into develop branch
  client/protocol_versions.json
  package.json
Labels: release

#752 Add traffic events for finalized blocks and transactions
  client/index.js
  common/constants.js
  monitoring/grafana.json
  node/index.js
  p2p/index.js
  p2p/server.js
  tools/transfer/sendTransferTx.js
  traffic/traffic-database.js
  traffic/traffic-stats-manager.js
  unittest/p2p.test.js
  unittest/traffic-database.test.js
  unittest/traffic-stats-manager.test.js
Labels: new feature

#755 [Bug] Fix minor tracker bugs
  tracker-server/network-topology.js
  tracker-server/tracker.js
Labels: bug

#756 Test for multiple node and os
  .github/workflows/github-actions.yml
  README.md
Labels: enhancement

#758 Add common/result-code.js for result code
  client/index.js
  common/common-util.js
  common/constants.js
  common/result-code.js
  consensus/consensus-util.js
  consensus/constants.js
  consensus/index.js
  db/functions.js
  db/index.js
  db/rule-util.js
  integration/blockchain.test.js
  integration/consensus.test.js
  integration/function.test.js
  integration/node.test.js
  json_rpc/index.js
  node/index.js
  tools/checkin/sendCloseCheckinTx.js
  tools/checkout/sendCloseCheckoutTx.js
  unittest/consensus.test.js
  unittest/db.test.js
  unittest/tx-pool.test.js
Labels: enhancement, new feature

#760 Fix flaky test cases with created_at tx field value
  unittest/test-util.js
  unittest/tx-pool.test.js
Labels: bug

#767 Set epoch_ms to 1000 for test blockchain configs
  blockchain-configs/1-node/blockchain_params.json
  blockchain-configs/1-node/genesis_block.json.gz
  blockchain-configs/2-nodes/blockchain_params.json
  blockchain-configs/2-nodes/genesis_block.json.gz
  blockchain-configs/3-nodes/blockchain_params.json
  blockchain-configs/3-nodes/genesis_block.json.gz
  unittest/test-util.js
Labels: enhancement

#763 Move to node-params.json and customize traffic params for sandbox environment
  blockchain-configs/afan-shard/node_params.json
  blockchain-configs/base/node_params.json
  blockchain-configs/he-shard/node_params.json
  blockchain-configs/sim-shard/node_params.json
  blockchain-configs/testnet-dev/node_params.json
  blockchain-configs/testnet-prod/node_params.json
  blockchain-configs/testnet-sandbox/node_params.json
  blockchain-configs/testnet-staging/node_params.json
  p2p/index.js
Labels: enhancement

#768 Reorg test code
  package.json
  test/data/accounts_for_testing.json
  test/data/functions_for_testing.json
  test/data/owners_for_testing.json
  test/data/rules_for_testing.json
  test/data/sharding_for_testing.json
  test/integration/blockchain.test.js
  test/integration/consensus.test.js
  test/integration/dapp.test.js
  test/integration/data/tx_adaccept_result.js
  test/integration/data/tx_adpropose_result.js
  test/integration/data/tx_crushOnPost_no_fan_result.js
  test/integration/data/tx_crushOnPost_two_fans_result.js
  test/integration/data/tx_crushOnReply_no_fan_result.js
  test/integration/data/tx_crushOnReply_three_fans_result.js
  test/integration/data/tx_invest_send_one_result.js
  test/integration/function.test.js
  test/integration/he_protocol.test.js
  test/integration/he_sharding.test.js
  test/integration/node.test.js
  test/integration/sharding.test.js
  test/test-util.js
  test/unit/block-pool.test.js
  test/unit/blockchain.test.js
  test/unit/common-util.test.js
  test/unit/consensus.test.js
  test/unit/db.test.js
  test/unit/event-handler.test.js
  test/unit/functions.test.js
  test/unit/p2p-util.test.js
  test/unit/p2p.test.js
  test/unit/radix-node.test.js
  test/unit/radix-tree.test.js
  test/unit/rule-util.test.js
  test/unit/state-manager.test.js
  test/unit/state-node.test.js
  test/unit/state-util.test.js
  test/unit/traffic-database.test.js
  test/unit/traffic-stats-manager.test.js
  test/unit/transaction.test.js
  test/unit/tx-pool.test.js
Labels: enhancement

#770 Fix a bug on single interval traffic database
  test/unit/traffic-database.test.js
  traffic/traffic-database.js
Labels: bug

#772 Do not call winstonLogger.debug() if DEBUG=false.
  logger/index.js
Labels: bug

#774 Fix check-in, check-out bugs
  blockchain-configs/1-node/genesis_block.json.gz
  blockchain-configs/2-nodes/genesis_block.json.gz
  blockchain-configs/3-nodes/genesis_block.json.gz
  blockchain-configs/afan-shard/genesis_block.json.gz
  blockchain-configs/base/genesis_block.json.gz
  blockchain-configs/base/genesis_rules.json
  blockchain-configs/he-shard/genesis_block.json.gz
  blockchain-configs/sim-shard/genesis_block.json.gz
  blockchain-configs/testnet-dev/genesis_block.json.gz
  blockchain-configs/testnet-prod/genesis_block.json.gz
  blockchain-configs/testnet-sandbox/genesis_block.json.gz
  blockchain-configs/testnet-staging/genesis_block.json.gz
  common/common-util.js
  common/result-code.js
  db/functions.js
  db/rule-util.js
  package.json
  test/integration/function.test.js
  tools/checkin/config_local.js
  tools/checkin/sendCloseCheckinTx.js
  tools/checkin/sendOpenCheckinTx.js
  tools/checkout/config_gcp.js
  tools/checkout/config_local.js
  tools/checkout/sendCloseCheckoutTx.js
  tools/checkout/sendOpenCheckoutTx.js
  yarn.lock
Labels: bug, enhancement

#777 Use bunyan as the default logger, add error catching
  .github/workflows/github-actions.yml
  common/constants.js
  deploy_blockchain_genesis_gcp.sh
  deploy_blockchain_incremental_gcp.sh
  deploy_blockchain_sandbox_gcp.sh
  logger/bunyan-util.js
  logger/index.js
  logger/winston-util.js
  package.json
  setup_blockchain_ubuntu.sh
  start_servers_local.sh
  yarn.lock
Labels: bug, enhancement

#778 Consensus tx clean-up in tx pool & fix bugs
  block-pool/index.js
  consensus/consensus-util.js
  consensus/constants.js
  consensus/index.js
  test/unit/tx-pool.test.js
  tx-pool/index.js
Labels: bug, enhancement

#783 Properly handle subtree write rules (do not allow non empty subtree write rules)
  blockchain-configs/1-node/genesis_block.json.gz
  blockchain-configs/2-nodes/genesis_block.json.gz
  blockchain-configs/3-nodes/genesis_block.json.gz
  blockchain-configs/afan-shard/genesis_block.json.gz
  blockchain-configs/base/genesis_block.json.gz
  blockchain-configs/base/genesis_functions.json
  blockchain-configs/base/genesis_rules.json
  blockchain-configs/he-shard/genesis_block.json.gz
  blockchain-configs/sim-shard/genesis_block.json.gz
  blockchain-configs/testnet-dev/genesis_block.json.gz
  blockchain-configs/testnet-prod/genesis_block.json.gz
  blockchain-configs/testnet-sandbox/genesis_block.json.gz
  blockchain-configs/testnet-staging/genesis_block.json.gz
  common/constants.js
  common/path-util.js
  common/result-code.js
  common/version-util.js
  db/functions.js
  db/index.js
  p2p/server.js
  rebuild_genesis_blocks.sh
  test/integration/blockchain.test.js
  test/integration/consensus.test.js
  test/integration/function.test.js
  test/integration/node.test.js
  test/integration/sharding.test.js
  test/test-util.js
  test/unit/common-util.test.js
  test/unit/consensus.test.js
  test/unit/db.test.js
  test/unit/functions.test.js
  test/unit/p2p.test.js
  test/unit/transaction.test.js
Labels: enhancement

#776 Add peer whitelist
  blockchain-configs/afan-shard/node_params.json
  blockchain-configs/base/node_params.json
  blockchain-configs/he-shard/node_params.json
  blockchain-configs/sim-shard/node_params.json
  blockchain-configs/testnet-dev/node_params.json
  blockchain-configs/testnet-prod/node_params.json
  blockchain-configs/testnet-sandbox/node_params.json
  blockchain-configs/testnet-staging/node_params.json
  common/common-util.js
  common/constants.js
  common/network-util.js
  p2p/index.js
  p2p/server.js
  p2p/util.js
  package.json
  start_node_genesis_gcp.sh
  start_node_incremental_gcp.sh
Labels: enhancement

#775 Deprecate GenesisToken and GenesisSharding
  blockchain-configs/1-node/genesis_block.json.gz
  blockchain-configs/2-nodes/genesis_block.json.gz
  blockchain-configs/3-nodes/genesis_block.json.gz
  blockchain-configs/afan-shard/genesis_block.json.gz
  blockchain-configs/base/genesis_block.json.gz
  blockchain-configs/he-shard/genesis_block.json.gz
  blockchain-configs/sim-shard/genesis_block.json.gz
  blockchain-configs/testnet-dev/genesis_block.json.gz
  blockchain-configs/testnet-prod/genesis_block.json.gz
  blockchain-configs/testnet-sandbox/genesis_block.json.gz
  blockchain-configs/testnet-staging/genesis_block.json.gz
  common/constants.js
  common/path-util.js
  db/functions.js
  db/index.js
  db/rule-util.js
  node/index.js
  p2p/server.js
  test/integration/function.test.js
  test/integration/he_sharding.test.js
  test/integration/node.test.js
  test/integration/sharding.test.js
  test/unit/db.test.js
  tools/genesis-file/createGenesisBlock.js
Labels: enhancement

#785 Fix consensus message clean-up from tx pool
  block-pool/index.js
  blockchain-configs/testnet-sandbox/blockchain_params.json
  blockchain-configs/testnet-sandbox/genesis_block.json.gz
  blockchain-configs/testnet-sandbox/node_params.json
  consensus/index.js
  test/unit/tx-pool.test.js
  tx-pool/index.js
Labels: bug

#789 Add propose / vote latency metrics to traffic stats
  common/constants.js
  monitoring/grafana.json
  node/index.js
Labels: enhancement

#788 Handle subtree owners properly
  common/result-code.js
  db/index.js
  db/state-util.js
  test/integration/function.test.js
  test/integration/node.test.js
  test/integration/sharding.test.js
  test/test-util.js
  test/unit/db.test.js
Labels: enhancement

#791 Add propose/vote p2p message latency to traffic stats
  client/index.js
  common/constants.js
  consensus/consensus-util.js
  consensus/index.js
  monitoring/grafana.json
  node/index.js
Labels: enhancement

#793 Allow writing with subtree owners in partial set cases (with isPartialSet = true)
  common/common-util.js
  db/index.js
  db/state-util.js
  test/integration/node.test.js
  test/integration/sharding.test.js
  test/unit/db.test.js
  test/unit/state-util.test.js
Labels: enhancement

#796 Enforce check-in, check-out ids to be same as the tx timestamp
  blockchain-configs/1-node/genesis_block.json.gz
  blockchain-configs/2-nodes/genesis_block.json.gz
  blockchain-configs/3-nodes/genesis_block.json.gz
  blockchain-configs/afan-shard/genesis_block.json.gz
  blockchain-configs/base/genesis_block.json.gz
  blockchain-configs/base/genesis_rules.json
  blockchain-configs/he-shard/genesis_block.json.gz
  blockchain-configs/sim-shard/genesis_block.json.gz
  blockchain-configs/testnet-dev/genesis_block.json.gz
  blockchain-configs/testnet-prod/genesis_block.json.gz
  blockchain-configs/testnet-sandbox/genesis_block.json.gz
  blockchain-configs/testnet-staging/genesis_block.json.gz
  db/rule-util.js
  test/integration/function.test.js
Labels: enhancement

#798 Feature/liayoo/p2p msg tags
  common/common-util.js
  common/constants.js
  consensus/index.js
  monitoring/grafana.json
  p2p/index.js
  p2p/server.js
Labels: new feature

#787 Deprecate ACCOUNT_INDEX
  README.md
  blockchain-configs/afan-shard/node_params.json
  blockchain-configs/base/node_params.json
  blockchain-configs/he-shard/node_params.json
  blockchain-configs/sim-shard/node_params.json
  blockchain-configs/testnet-dev/node_params.json
  blockchain-configs/testnet-prod/node_params.json
  blockchain-configs/testnet-sandbox/node_params.json
  blockchain-configs/testnet-staging/node_params.json
  common/constants.js
  deploy_blockchain_genesis_gcp.sh
  deploy_blockchain_incremental_gcp.sh
  deploy_blockchain_sandbox_gcp.sh
  inject_account_gcp.js
  json_rpc/index.js
  logger/bunyan-util.js
  logger/winston-util.js
  node/index.js
  package.json
  start_node_genesis_gcp.sh
  start_node_incremental_gcp.sh
  start_servers_afan_local.sh
  start_servers_local.sh
  test/integration/blockchain.test.js
  test/integration/consensus.test.js
  test/integration/dapp.test.js
  test/integration/function.test.js
  test/integration/he_protocol.test.js
  test/integration/he_sharding.test.js
  test/integration/node.test.js
  test/integration/sharding.test.js
  tracker-server/tracker.js
Labels: enhancement, new feature

#794 Feature/liayoo/client api access control
  blockchain-configs/afan-shard/node_params.json
  blockchain-configs/base/node_params.json
  blockchain-configs/he-shard/node_params.json
  blockchain-configs/sim-shard/node_params.json
  blockchain-configs/testnet-dev/node_params.json
  blockchain-configs/testnet-prod/node_params.json
  blockchain-configs/testnet-sandbox/node_params.json
  blockchain-configs/testnet-staging/node_params.json
  client/index.js
  common/constants.js
  common/result-code.js
  json_rpc/account.js
  json_rpc/api-access.js
  json_rpc/block.js
  json_rpc/database.js
  json_rpc/event-handler.js
  json_rpc/index.js
  json_rpc/json-rpc-util.js
  json_rpc/network.js
  json_rpc/transaction.js
  json_rpc/version.js
  node/index.js
  package.json
  start_node_genesis_gcp.sh
  start_node_incremental_gcp.sh
  tools/api-access/addToDevClientApiIpWhitelist.js
  tools/api-access/getDevClientApiIpWhitelist.js
  tools/api-access/removeFromDevClientApiIpWhitelist.js
  tools/api-access/util.js
  yarn.lock
Labels: new feature

#804 Fix typos & missing things in the deploy scripts.
  deploy_blockchain_incremental_gcp.sh
  deploy_blockchain_sandbox_gcp.sh
Labels: bug

#803 [BUG] Correctly check max inbound
  p2p/index.js
  p2p/server.js
  p2p/util.js
Labels: bug

#812 Fix ip validity checking
  json_rpc/api-access.js
  tools/api-access/addToDevClientApiIpWhitelist.js
  tools/api-access/removeFromDevClientApiIpWhitelist.js
Labels: bug

#810 Reorg peer connections periodically
  blockchain-configs/afan-shard/node_params.json
  blockchain-configs/base/node_params.json
  blockchain-configs/he-shard/node_params.json
  blockchain-configs/sim-shard/node_params.json
  blockchain-configs/testnet-dev/node_params.json
  blockchain-configs/testnet-prod/node_params.json
  blockchain-configs/testnet-sandbox/node_params.json
  blockchain-configs/testnet-staging/node_params.json
  monitoring/grafana.json
  p2p/index.js
  test/unit/p2p.test.js
Labels: bug, enhancement, new feature

#814 Allow removal of wildcard ip whitelist
  json_rpc/api-access.js
Labels: enhancement

#808 Fix deployment test in acations
  .github/workflows/github-actions.yml
  tools/cicd/deployment.js
Labels: bug

#806 Add subtree function triggering
  blockchain-configs/1-node/blockchain_params.json
  blockchain-configs/1-node/genesis_block.json.gz
  blockchain-configs/2-nodes/blockchain_params.json
  blockchain-configs/2-nodes/genesis_block.json.gz
  blockchain-configs/3-nodes/blockchain_params.json
  blockchain-configs/3-nodes/genesis_block.json.gz
  blockchain-configs/afan-shard/blockchain_params.json
  blockchain-configs/afan-shard/genesis_block.json.gz
  blockchain-configs/base/blockchain_params.json
  blockchain-configs/base/genesis_block.json.gz
  blockchain-configs/he-shard/blockchain_params.json
  blockchain-configs/he-shard/genesis_block.json.gz
  blockchain-configs/sim-shard/blockchain_params.json
  blockchain-configs/sim-shard/genesis_block.json.gz
  blockchain-configs/testnet-dev/blockchain_params.json
  blockchain-configs/testnet-dev/genesis_block.json.gz
  blockchain-configs/testnet-prod/blockchain_params.json
  blockchain-configs/testnet-prod/genesis_block.json.gz
  blockchain-configs/testnet-sandbox/blockchain_params.json
  blockchain-configs/testnet-sandbox/genesis_block.json.gz
  blockchain-configs/testnet-staging/blockchain_params.json
  blockchain-configs/testnet-staging/genesis_block.json.gz
  common/common-util.js
  common/constants.js
  common/result-code.js
  db/functions.js
  db/index.js
  db/radix-node.js
  db/radix-tree.js
  db/state-manager.js
  db/state-node.js
  db/state-util.js
  node/index.js
  package.json
  test/integration/function.test.js
  test/integration/node.test.js
  test/test-util.js
  test/unit/common-util.test.js
  test/unit/db.test.js
  test/unit/functions.test.js
  test/unit/radix-node.test.js
  test/unit/radix-tree.test.js
  test/unit/state-manager.test.js
  test/unit/state-node.test.js
  test/unit/state-util.test.js
  tools/genesis-file/createGenesisBlock.js
  tools/proof-hash/verifyProof.js
  tools/proof-hash/verifySnapshot.js
Labels: enhancement, new feature

#818 Add gc_num_siblings_deleted to state rule
  blockchain-configs/1-node/genesis_block.json.gz
  blockchain-configs/2-nodes/genesis_block.json.gz
  blockchain-configs/3-nodes/genesis_block.json.gz
  blockchain-configs/afan-shard/blockchain_params.json
  blockchain-configs/afan-shard/genesis_block.json.gz
  blockchain-configs/base/blockchain_params.json
  blockchain-configs/base/genesis_block.json.gz
  blockchain-configs/base/genesis_rules.json
  blockchain-configs/he-shard/blockchain_params.json
  blockchain-configs/he-shard/genesis_block.json.gz
  blockchain-configs/sim-shard/blockchain_params.json
  blockchain-configs/sim-shard/genesis_block.json.gz
  blockchain-configs/testnet-dev/blockchain_params.json
  blockchain-configs/testnet-dev/genesis_block.json.gz
  blockchain-configs/testnet-prod/blockchain_params.json
  blockchain-configs/testnet-prod/genesis_block.json.gz
  blockchain-configs/testnet-sandbox/blockchain_params.json
  blockchain-configs/testnet-sandbox/genesis_block.json.gz
  blockchain-configs/testnet-staging/blockchain_params.json
  blockchain-configs/testnet-staging/genesis_block.json.gz
  common/constants.js
  db/index.js
  db/state-util.js
  p2p/server.js
  test/unit/db.test.js
  test/unit/state-util.test.js
Labels: enhancement, new feature

#816 Return usage, available, staking info for apps
  blockchain-configs/1-node/blockchain_params.json
  blockchain-configs/1-node/genesis_block.json.gz
  blockchain-configs/2-nodes/blockchain_params.json
  blockchain-configs/2-nodes/genesis_block.json.gz
  blockchain-configs/3-nodes/blockchain_params.json
  blockchain-configs/3-nodes/genesis_block.json.gz
  blockchain-configs/afan-shard/blockchain_params.json
  blockchain-configs/afan-shard/genesis_block.json.gz
  blockchain-configs/base/blockchain_params.json
  blockchain-configs/base/genesis_block.json.gz
  blockchain-configs/he-shard/blockchain_params.json
  blockchain-configs/he-shard/genesis_block.json.gz
  blockchain-configs/sim-shard/blockchain_params.json
  blockchain-configs/sim-shard/genesis_block.json.gz
  blockchain-configs/testnet-dev/blockchain_params.json
  blockchain-configs/testnet-dev/genesis_block.json.gz
  blockchain-configs/testnet-prod/blockchain_params.json
  blockchain-configs/testnet-prod/genesis_block.json.gz
  blockchain-configs/testnet-sandbox/blockchain_params.json
  blockchain-configs/testnet-sandbox/genesis_block.json.gz
  blockchain-configs/testnet-staging/blockchain_params.json
  blockchain-configs/testnet-staging/genesis_block.json.gz
  client/index.js
  json_rpc/database.js
  node/index.js
  test/integration/node.test.js
  test/unit/db.test.js
Labels: enhancement

#820 Add resource/min_gc_num_siblings_deleted blockchain param
  blockchain-configs/1-node/blockchain_params.json
  blockchain-configs/1-node/genesis_block.json.gz
  blockchain-configs/2-nodes/blockchain_params.json
  blockchain-configs/2-nodes/genesis_block.json.gz
  blockchain-configs/3-nodes/blockchain_params.json
  blockchain-configs/3-nodes/genesis_block.json.gz
  blockchain-configs/afan-shard/blockchain_params.json
  blockchain-configs/afan-shard/genesis_block.json.gz
  blockchain-configs/base/blockchain_params.json
  blockchain-configs/base/genesis_block.json.gz
  blockchain-configs/he-shard/blockchain_params.json
  blockchain-configs/he-shard/genesis_block.json.gz
  blockchain-configs/sim-shard/blockchain_params.json
  blockchain-configs/sim-shard/genesis_block.json.gz
  blockchain-configs/testnet-dev/blockchain_params.json
  blockchain-configs/testnet-dev/genesis_block.json.gz
  blockchain-configs/testnet-prod/blockchain_params.json
  blockchain-configs/testnet-prod/genesis_block.json.gz
  blockchain-configs/testnet-sandbox/blockchain_params.json
  blockchain-configs/testnet-sandbox/genesis_block.json.gz
  blockchain-configs/testnet-staging/blockchain_params.json
  blockchain-configs/testnet-staging/genesis_block.json.gz
  consensus/index.js
  db/index.js
  db/state-util.js
  test/test-util.js
  test/unit/state-util.test.js
Labels: enhancement

#822 Add BLOCK_FINALIZED traffic event for finalization latency
  common/constants.js
  monitoring/grafana.json
  node/index.js
Labels: enhancement

#819 Update p2p state
  README.md
  blockchain-configs/afan-shard/node_params.json
  blockchain-configs/base/node_params.json
  blockchain-configs/he-shard/node_params.json
  blockchain-configs/sim-shard/node_params.json
  blockchain-configs/testnet-dev/node_params.json
  blockchain-configs/testnet-prod/node_params.json
  blockchain-configs/testnet-sandbox/node_params.json
  blockchain-configs/testnet-staging/node_params.json
  db/rule-util.js
  p2p/index.js
  p2p/p2p-util.js
  p2p/server.js
  p2p/util.js
  package.json
  start_servers_afan_local.sh
  start_servers_local.sh
  test/unit/p2p-util.test.js
  tracker-server/tracker.js
Labels: bug, enhancement

#823 Reorg grafana.json
  monitoring/grafana.json
Labels: enhancement

#824 Increase min_gc_num_siblings_deleted to 100
  blockchain-configs/1-node/blockchain_params.json
  blockchain-configs/1-node/genesis_block.json.gz
  blockchain-configs/2-nodes/blockchain_params.json
  blockchain-configs/2-nodes/genesis_block.json.gz
  blockchain-configs/3-nodes/blockchain_params.json
  blockchain-configs/3-nodes/genesis_block.json.gz
  blockchain-configs/afan-shard/blockchain_params.json
  blockchain-configs/afan-shard/genesis_block.json.gz
  blockchain-configs/base/blockchain_params.json
  blockchain-configs/base/genesis_block.json.gz
  blockchain-configs/base/genesis_rules.json
  blockchain-configs/he-shard/blockchain_params.json
  blockchain-configs/he-shard/genesis_block.json.gz
  blockchain-configs/sim-shard/blockchain_params.json
  blockchain-configs/sim-shard/genesis_block.json.gz
  blockchain-configs/testnet-dev/blockchain_params.json
  blockchain-configs/testnet-dev/genesis_block.json.gz
  blockchain-configs/testnet-prod/blockchain_params.json
  blockchain-configs/testnet-prod/genesis_block.json.gz
  blockchain-configs/testnet-sandbox/blockchain_params.json
  blockchain-configs/testnet-sandbox/genesis_block.json.gz
  blockchain-configs/testnet-staging/blockchain_params.json
  blockchain-configs/testnet-staging/genesis_block.json.gz
  p2p/index.js
  p2p/server.js
  test/integration/blockchain.test.js
  test/integration/consensus.test.js
  test/integration/dapp.test.js
  test/integration/function.test.js
  test/integration/he_protocol.test.js
  test/integration/he_sharding.test.js
  test/integration/node.test.js
  test/integration/sharding.test.js
  test/unit/db.test.js
Labels: bug, enhancement

#821 Feature/liayoo/query limits
  blockchain-configs/1-node/blockchain_params.json
  blockchain-configs/1-node/genesis_block.json.gz
  blockchain-configs/2-nodes/blockchain_params.json
  blockchain-configs/2-nodes/genesis_block.json.gz
  blockchain-configs/3-nodes/blockchain_params.json
  blockchain-configs/3-nodes/genesis_block.json.gz
  blockchain-configs/afan-shard/blockchain_params.json
  blockchain-configs/afan-shard/genesis_block.json.gz
  blockchain-configs/afan-shard/node_params.json
  blockchain-configs/base/blockchain_params.json
  blockchain-configs/base/genesis_block.json.gz
  blockchain-configs/base/node_params.json
  blockchain-configs/he-shard/blockchain_params.json
  blockchain-configs/he-shard/genesis_block.json.gz
  blockchain-configs/he-shard/node_params.json
  blockchain-configs/sim-shard/blockchain_params.json
  blockchain-configs/sim-shard/genesis_block.json.gz
  blockchain-configs/sim-shard/node_params.json
  blockchain-configs/testnet-dev/blockchain_params.json
  blockchain-configs/testnet-dev/genesis_block.json.gz
  blockchain-configs/testnet-dev/node_params.json
  blockchain-configs/testnet-prod/blockchain_params.json
  blockchain-configs/testnet-prod/genesis_block.json.gz
  blockchain-configs/testnet-prod/node_params.json
  blockchain-configs/testnet-sandbox/blockchain_params.json
  blockchain-configs/testnet-sandbox/genesis_block.json.gz
  blockchain-configs/testnet-sandbox/node_params.json
  blockchain-configs/testnet-staging/blockchain_params.json
  blockchain-configs/testnet-staging/genesis_block.json.gz
  blockchain-configs/testnet-staging/node_params.json
  client/index.js
  common/common-util.js
  common/result-code.js
  db/index.js
  json_rpc/database.js
  p2p/server.js
  test/integration/node.test.js
  test/unit/db.test.js
Labels: new feature

#827 [Bug] Check whitelisting when connection
  p2p/index.js
  p2p/server.js
Labels: bug

#829 Feature/liayoo/block rewards
  blockchain-configs/1-node/blockchain_params.json
  blockchain-configs/1-node/genesis_block.json.gz
  blockchain-configs/2-nodes/blockchain_params.json
  blockchain-configs/2-nodes/genesis_block.json.gz
  blockchain-configs/3-nodes/blockchain_params.json
  blockchain-configs/3-nodes/genesis_block.json.gz
  blockchain-configs/afan-shard/blockchain_params.json
  blockchain-configs/afan-shard/genesis_block.json.gz
  blockchain-configs/base/blockchain_params.json
  blockchain-configs/base/genesis_block.json.gz
  blockchain-configs/he-shard/blockchain_params.json
  blockchain-configs/he-shard/genesis_block.json.gz
  blockchain-configs/sim-shard/blockchain_params.json
  blockchain-configs/sim-shard/genesis_block.json.gz
  blockchain-configs/testnet-dev/blockchain_params.json
  blockchain-configs/testnet-dev/genesis_block.json.gz
  blockchain-configs/testnet-prod/blockchain_params.json
  blockchain-configs/testnet-prod/genesis_block.json.gz
  blockchain-configs/testnet-sandbox/blockchain_params.json
  blockchain-configs/testnet-sandbox/genesis_block.json.gz
  blockchain-configs/testnet-staging/blockchain_params.json
  blockchain-configs/testnet-staging/genesis_block.json.gz
  common/constants.js
  db/functions.js
  db/index.js
  test/integration/consensus.test.js
  test/unit/functions.test.js
  test/unit/p2p.test.js
  tools/genesis-file/createGenesisBlock.js
Labels: enhancement

#830 Add grafana panels for num_peer_candidates
  monitoring/grafana.json
Labels: enhancement

#833 Feature/liayoo/error message convention
  common/common-util.js
  common/network-util.js
  db/index.js
  test/integration/consensus.test.js
  test/integration/function.test.js
  test/integration/node.test.js
  test/unit/common-util.test.js
  test/unit/db.test.js
  tools/checkin/sendCloseCheckinTx.js
  tools/checkout/sendCloseCheckoutTx.js
  tools/util.js
  tools/verify-tx/sample_tx.json
Labels: enhancement

#832 Feature/minsulee2/keep more api nodes
  p2p/index.js
Labels: enhancement

#837 Fix isAlive always true bug
  start_node_genesis_gcp.sh
  tools/chatbot/config_gcp.js
  tools/checkin/config_gcp.js
  tools/checkin/config_local.js
  tools/checkin/sendOpenCheckinTx.js
  tools/checkout/config_gcp.js
  tools/checkout/config_local.js
  tools/checkout/sendOpenCheckoutTx.js
  tools/escrow/config_gcp.js
  tools/payments/config_gcp.js
  tools/transfer/config_gcp.js
  tracker-server/tracker.js
Labels: bug

#838 Feature/liayoo/extend state rule
  common/constants.js
  db/index.js
  db/state-util.js
  test/unit/db.test.js
  test/unit/state-util.test.js
Labels: new feature

#839 Feature/liayoo/multi cmd tool
  tools/multi-commands/commands/gcloudUpdateMachineTypeCommands.txt
  tools/multi-commands/commands/localCreateGenesisBlockCommands.txt
  tools/multi-commands/runCmdsSequentially.js
Labels: new feature

#847 Ignore minimalNTPLatencyDelta that's too big/small
  consensus/index.js
Labels: bug

#850 Correctly get GPT2 version compatibility
  tools/cicd/deployment.js
Labels: bug

#852 Fix missing chainId in ecRecoverPub()
  block-pool/index.js
  blockchain-configs/mainnet-prod/blockchain_params.json
  blockchain-configs/mainnet-prod/genesis_block.json.gz
  blockchain-configs/testnet-prod/genesis_block.json.gz
  common/common-util.js
  consensus/consensus-util.js
  consensus/index.js
  db/index.js
  node/index.js
  p2p/p2p-util.js
  p2p/server.js
  package.json
  tools/genesis-file/createGenesisBlock.js
  tx-pool/transaction.js
  yarn.lock
Labels: bug, enhancement

#851 Add #num_children property to state info
  common/constants.js
  db/index.js
  db/state-node.js
  p2p/server.js
  test/integration/node.test.js
  test/unit/db.test.js
  test/unit/p2p.test.js
  test/unit/state-node.test.js
  test/unit/state-util.test.js
Labels: enhancement, new feature

#855 Handle write rule syntax errors properly
  common/result-code.js
  db/functions.js
  db/index.js
  test/unit/db.test.js
Labels: enhancement

#856 Add num_accounts grafana panel
  monitoring/grafana.json
Labels: enhancement

#857 Fix api access tool scripts
  tools/api-access/addToDevClientApiIpWhitelist.js
  tools/api-access/removeFromDevClientApiIpWhitelist.js
  tools/api-access/util.js
Labels: bug

#854 Add validator whitelist
  blockchain-configs/1-node/blockchain_params.json
  blockchain-configs/1-node/genesis_block.json.gz
  blockchain-configs/2-nodes/blockchain_params.json
  blockchain-configs/2-nodes/genesis_block.json.gz
  blockchain-configs/3-nodes/blockchain_params.json
  blockchain-configs/3-nodes/genesis_block.json.gz
  blockchain-configs/afan-shard/blockchain_params.json
  blockchain-configs/afan-shard/genesis_block.json.gz
  blockchain-configs/base/blockchain_params.json
  blockchain-configs/base/genesis_block.json.gz
  blockchain-configs/base/genesis_rules.json
  blockchain-configs/he-shard/blockchain_params.json
  blockchain-configs/he-shard/genesis_block.json.gz
  blockchain-configs/mainnet-prod/blockchain_params.json
  blockchain-configs/mainnet-prod/genesis_block.json.gz
  blockchain-configs/sim-shard/blockchain_params.json
  blockchain-configs/sim-shard/genesis_block.json.gz
  blockchain-configs/testnet-dev/blockchain_params.json
  blockchain-configs/testnet-dev/genesis_block.json.gz
  blockchain-configs/testnet-prod/blockchain_params.json
  blockchain-configs/testnet-prod/genesis_block.json.gz
  blockchain-configs/testnet-sandbox/blockchain_params.json
  blockchain-configs/testnet-sandbox/genesis_block.json.gz
  blockchain-configs/testnet-staging/blockchain_params.json
  blockchain-configs/testnet-staging/genesis_block.json.gz
  common/constants.js
  common/path-util.js
  common/result-code.js
  consensus/index.js
  db/rule-util.js
  test/integration/consensus.test.js
  test/unit/consensus.test.js
  tools/genesis-file/createGenesisBlock.js
Labels: bug, new feature

#860 Expose safe env variables only by /get_config
  common/constants.js
  p2p/index.js
  tracker-server/tracker.js
Labels: enhancement

#859 Merge release/v1.0.0 into develop branch
  README.md
  client/protocol_versions.json
  package.json
Labels: release

#863 Add dup check for variable labels in state paths
  db/index.js
  db/state-util.js
  monitoring/grafana.json
  test/unit/state-util.test.js
Labels: enhancement, new feature

#867 Add ObjectUtil to split or construct an object to/from chunks
  common/object-util.js
  package.json
  test/unit/object-util.test.js
Labels: new feature

#865 Use stream for writing blocks & snapshots
  blockchain-configs/1-node/blockchain_params.json
  blockchain-configs/1-node/genesis_block.json.gz
  blockchain-configs/2-nodes/blockchain_params.json
  blockchain-configs/2-nodes/genesis_block.json.gz
  blockchain-configs/3-nodes/blockchain_params.json
  blockchain-configs/3-nodes/genesis_block.json.gz
  blockchain-configs/afan-shard/blockchain_params.json
  blockchain-configs/afan-shard/genesis_block.json.gz
  blockchain-configs/base/blockchain_params.json
  blockchain-configs/base/genesis_block.json.gz
  blockchain-configs/he-shard/blockchain_params.json
  blockchain-configs/he-shard/genesis_block.json.gz
  blockchain-configs/mainnet-prod/blockchain_params.json
  blockchain-configs/mainnet-prod/genesis_block.json.gz
  blockchain-configs/sim-shard/blockchain_params.json
  blockchain-configs/sim-shard/genesis_block.json.gz
  blockchain-configs/testnet-dev/blockchain_params.json
  blockchain-configs/testnet-dev/genesis_block.json.gz
  blockchain-configs/testnet-prod/blockchain_params.json
  blockchain-configs/testnet-prod/genesis_block.json.gz
  blockchain-configs/testnet-sandbox/blockchain_params.json
  blockchain-configs/testnet-sandbox/genesis_block.json.gz
  blockchain-configs/testnet-staging/blockchain_params.json
  blockchain-configs/testnet-staging/genesis_block.json.gz
  blockchain/index.js
  common/file-util.js
  common/object-util.js
  consensus/index.js
  node/index.js
  p2p/index.js
  package.json
  test/test-util.js
  test/unit/block-pool.test.js
  test/unit/blockchain.test.js
  test/unit/consensus.test.js
  test/unit/db.test.js
  test/unit/functions.test.js
  test/unit/p2p.test.js
  test/unit/transaction.test.js
  test/unit/tx-pool.test.js
  yarn.lock
Labels: bug, enhancement

#871 Increase MAX_NUM_INBOUND_CONNECTION, fix peer connection
  blockchain-configs/base/node_params.json
  blockchain-configs/he-shard/node_params.json
  blockchain-configs/mainnet-prod/node_params.json
  blockchain-configs/sim-shard/node_params.json
  blockchain-configs/testnet-dev/node_params.json
  blockchain-configs/testnet-prod/node_params.json
  blockchain-configs/testnet-sandbox/node_params.json
  blockchain-configs/testnet-staging/node_params.json
  p2p/index.js
  test/unit/p2p.test.js
Labels: bug

#870 Added min_gas_price resource blockchain param
  blockchain-configs/1-node/blockchain_params.json
  blockchain-configs/1-node/genesis_block.json.gz
  blockchain-configs/2-nodes/blockchain_params.json
  blockchain-configs/2-nodes/genesis_block.json.gz
  blockchain-configs/3-nodes/blockchain_params.json
  blockchain-configs/3-nodes/genesis_block.json.gz
  blockchain-configs/afan-shard/blockchain_params.json
  blockchain-configs/afan-shard/genesis_block.json.gz
  blockchain-configs/base/blockchain_params.json
  blockchain-configs/base/genesis_block.json.gz
  blockchain-configs/he-shard/blockchain_params.json
  blockchain-configs/he-shard/genesis_block.json.gz
  blockchain-configs/mainnet-prod/blockchain_params.json
  blockchain-configs/mainnet-prod/genesis_block.json.gz
  blockchain-configs/sim-shard/blockchain_params.json
  blockchain-configs/sim-shard/genesis_block.json.gz
  blockchain-configs/testnet-dev/blockchain_params.json
  blockchain-configs/testnet-dev/genesis_block.json.gz
  blockchain-configs/testnet-prod/blockchain_params.json
  blockchain-configs/testnet-prod/genesis_block.json.gz
  blockchain-configs/testnet-sandbox/blockchain_params.json
  blockchain-configs/testnet-sandbox/genesis_block.json.gz
  blockchain-configs/testnet-staging/blockchain_params.json
  blockchain-configs/testnet-staging/genesis_block.json.gz
  common/result-code.js
  consensus/index.js
  db/index.js
  tools/genesis-file/createGenesisBlock.js
Labels: enhancement

#869 Remove some TODOs that are not applicable
  db/index.js
  p2p/server.js
Labels: enhancement

#872 Fix missing chain ids.
  json_rpc/transaction.js
Labels: bug

#873 Fix grafana for root_state_info metrics
  monitoring/grafana.json
Labels: bug

#868 Set genesis_timestamp
  blockchain-configs/1-node/blockchain_params.json
  blockchain-configs/1-node/genesis_block.json.gz
  blockchain-configs/2-nodes/blockchain_params.json
  blockchain-configs/2-nodes/genesis_block.json.gz
  blockchain-configs/3-nodes/blockchain_params.json
  blockchain-configs/3-nodes/genesis_block.json.gz
  blockchain-configs/afan-shard/blockchain_params.json
  blockchain-configs/afan-shard/genesis_block.json.gz
  blockchain-configs/base/blockchain_params.json
  blockchain-configs/base/genesis_block.json.gz
  blockchain-configs/he-shard/blockchain_params.json
  blockchain-configs/he-shard/genesis_block.json.gz
  blockchain-configs/mainnet-prod/blockchain_params.json
  blockchain-configs/mainnet-prod/genesis_block.json.gz
  blockchain-configs/sim-shard/blockchain_params.json
  blockchain-configs/sim-shard/genesis_block.json.gz
  blockchain-configs/testnet-dev/blockchain_params.json
  blockchain-configs/testnet-dev/genesis_block.json.gz
  blockchain-configs/testnet-prod/blockchain_params.json
  blockchain-configs/testnet-prod/genesis_block.json.gz
  blockchain-configs/testnet-sandbox/blockchain_params.json
  blockchain-configs/testnet-sandbox/genesis_block.json.gz
  blockchain-configs/testnet-staging/blockchain_params.json
  blockchain-configs/testnet-staging/genesis_block.json.gz
Labels: enhancement
