Repository ainblockchain/ain-blockchain, pull requests merged in 2021-08, with the labels that each got.

#516 Fix memory issue by applying incremental block file loading
  blockchain/block.js
  blockchain/index.js
  common/constants.js
  common/file-util.js
  node/index.js
  unittest/blockchain.test.js
Labels: bug

#518 Add experimental code for optimizing receipt proof hash computation
  common/constants.js
  common/path-util.js
  db/index.js
Labels: new feature

#521 Merge release/v0.9.0 into develop branch
  client/protocol_versions.json
  package.json
Labels: release

#525 Hotfix/deployment check fix
  tools/cicd/deployment.js
Labels: bug

#524 Use numeric error code for function triggering
  common/common-util.js
  common/constants.js
  db/functions.js
  db/index.js
  genesis-configs/afan-shard/genesis_params.json
  genesis-configs/base/genesis_params.json
  genesis-configs/sim-shard/genesis_params.json
  genesis-configs/testnet/genesis_params.json
  integration/afan_dapp.test.js
  integration/blockchain.test.js
  integration/consensus.test.js
  integration/node.test.js
  integration/sharding.test.js
  package.json
  tools/checkout/sendCloseCheckoutTx.js
  unittest/common-util.test.js
  unittest/db.test.js
  unittest/functions.test.js
  unittest/test-util.js
Labels: enhancement

#528 Reduce flakiness of integration tests due to tree bytes interference
  integration/node.test.js
Labels: enhancement

#532 Apply chain id
  client/index.js
  common/common-util.js
  common/network-util.js
  genesis-configs/afan-shard/genesis_params.json
  genesis-configs/afan-shard/genesis_token.json
  genesis-configs/base/genesis_params.json
  genesis-configs/base/genesis_token.json
  genesis-configs/sim-shard/genesis_params.json
  genesis-configs/sim-shard/genesis_token.json
  genesis-configs/testnet/genesis_params.json
  genesis-configs/testnet/genesis_token.json
  json_rpc/index.js
  p2p/index.js
  p2p/server.js
  p2p/util.js
  tools/util.js
  tx-pool/transaction.js
  unittest/db.test.js
  unittest/p2p-util.test.js
Labels: new feature

#533 Always deploy both genesis and incremental scripts
  deploy_blockchain_genesis_gcp.sh
  deploy_blockchain_incremental_gcp.sh
Labels: enhancement

#534 Set testnet chain id as 0
  genesis-configs/testnet/genesis_params.json
Labels: bug

#535 Implement radix tree
  common/common-util.js
  db/radix-node.js
  db/radix-tree.js
  db/rule-util.js
  db/state-node.js
  package.json
  unittest/common-util.test.js
  unittest/radix-node.test.js
  unittest/radix-tree.test.js
  unittest/rule-util.test.js
Labels: new feature

#541 Add set / update / verify proof hash APIs
  db/radix-node.js
  db/radix-tree.js
  db/state-node.js
  unittest/radix-node.test.js
  unittest/radix-tree.test.js
Labels: new feature

#546 Use array-based radix child map in radix node
  common/constants.js
  db/radix-child-map.js
  db/radix-node.js
  db/radix-tree.js
  db/state-node.js
  integration/node.test.js
  package.json
  unittest/db.test.js
  unittest/radix-child-map.test.js
  unittest/state-node.test.js
Labels: enhancement, new feature

#547 Turn off enableStateTreeTransfer flag by default.
  common/constants.js
Labels: enhancement

#549 Use startWith() instead of slice()
  db/radix-tree.js
Labels: enhancement

#550 Use a cache for hex labels
  common/constants.js
  db/radix-tree.js
  unittest/radix-tree.test.js
Labels: enhancement
