Repository ainblockchain/ain-blockchain, pull requests merged in 2022-01, with the labels that each got.

#866 Release/v1.0.1
  blockchain-configs/1-node/blockchain_params.json
  blockchain-configs/1-node/genesis_block.json.gz
  blockchain-configs/2-nodes/blockchain_params.json
  blockchain-configs/2-nodes/genesis_block.json.gz
  blockchain-configs/3-nodes/blockchain_params.json
  blockchain-configs/3-nodes/genesis_block.json.gz
  blockchain-configs/afan-shard/blockchain_params.json
  blockchain-configs/afan-shard/genesis_block.json.gz
  blockchain-configs/base/blockchain_params.json
  blockchain-configs/base/genesis_block.json.gz
  blockchain-configs/base/node_params.json
  blockchain-configs/he-shard/blockchain_params.json
  blockchain-configs/he-shard/genesis_block.json.gz
  blockchain-configs/he-shard/node_params.json
  blockchain-configs/mainnet-prod/blockchain_params.json
  blockchain-configs/mainnet-prod/genesis_block.json.gz
  blockchain-configs/mainnet-prod/node_params.json
  blockchain-configs/sim-shard/blockchain_params.json
  blockchain-configs/sim-shard/genesis_block.json.gz
  blockchain-configs/sim-shard/node_params.json
  blockchain-configs/testnet-dev/blockchain_params.json
  blockchain-configs/testnet-dev/genesis_block.json.gz
  blockchain-configs/testnet-dev/node_params.json
  blockchain-configs/testnet-prod/blockchain_params.json
  blockchain-configs/testnet-prod/genesis_block.json.gz
  blockchain-configs/testnet-prod/node_params.json
  blockchain-configs/testnet-sandbox/blockchain_params.json
  blockchain-configs/testnet-sandbox/genesis_block.json.gz
  blockchain-configs/testnet-sandbox/node_params.json
  blockchain-configs/testnet-staging/blockchain_params.json
  blockchain-configs/testnet-staging/genesis_block.json.gz
  blockchain-configs/testnet-staging/node_params.json
  blockchain/index.js
  client/protocol_versions.json
  common/file-util.js
  common/object-util.js
  common/result-code.js
  consensus/index.js
  db/index.js
  db/state-util.js
  json_rpc/transaction.js
  monitoring/grafana.json
  node/index.js
  p2p/index.js
  p2p/server.js
  package.json
  test/test-util.js
  test/unit/block-pool.test.js
  test/unit/blockchain.test.js
  test/unit/consensus.test.js
  test/unit/db.test.js
  test/unit/functions.test.js
  test/unit/object-util.test.js
  test/unit/p2p.test.js
  test/unit/state-util.test.js
  test/unit/transaction.test.js
  test/unit/tx-pool.test.js
  tools/genesis-file/createGenesisBlock.js
  yarn.lock
Labels: release

#874 Merge Release/v1.0.1 into develop
  client/protocol_versions.json
  package.json
Labels: release

#877 Add more monitoring metrics
  common/constants.js
  consensus/index.js
  monitoring/grafana.json
  node/index.js
  p2p/index.js
  p2p/server.js
  test/unit/p2p.test.js
Labels: new feature

#878 Change objects to Maps
  block-pool/index.js
  client/index.js
  consensus/index.js
  node/index.js
  p2p/server.js
  test/integration/consensus.test.js
  test/integration/function.test.js
  test/integration/node.test.js
  test/integration/sharding.test.js
  test/unit/block-pool.test.js
  test/unit/tx-pool.test.js
  tx-pool/index.js
Labels: enhancement

#883 Add chainId, networkId to rest function call data.
  db/functions.js
  db/index.js
Labels: enhancement

#884 Fix state available info for free tier apps.
  node/index.js
Labels: bug

#885 Set axios timeout
  afan_client/request_manager.js
  blockchain-configs/afan-shard/node_params.json
  blockchain-configs/base/node_params.json
  blockchain-configs/he-shard/node_params.json
  blockchain-configs/mainnet-prod/node_params.json
  blockchain-configs/sim-shard/node_params.json
  blockchain-configs/testnet-dev/node_params.json
  blockchain-configs/testnet-prod/node_params.json
  blockchain-configs/testnet-sandbox/node_params.json
  blockchain-configs/testnet-staging/node_params.json
  common/network-util.js
  db/functions.js
Labels: enhancement

#881 Add TimerFlags feature
  block-pool/index.js
  blockchain-configs/base/timer_flags.json
  blockchain-configs/mainnet-prod/timer_flags.json
  blockchain-configs/testnet-prod/timer_flags.json
  blockchain/index.js
  common/common-util.js
  common/constants.js
  consensus/index.js
  db/rule-util.js
  db/state-util.js
  node/index.js
  test/test-util.js
  test/unit/common-util.test.js
  test/unit/state-util.test.js
Labels: new feature

#886 Show richer welcome messages
  blockchain-configs/afan-shard/node_params.json
  blockchain-configs/base/node_params.json
  blockchain-configs/he-shard/node_params.json
  blockchain-configs/mainnet-prod/node_params.json
  blockchain-configs/sim-shard/node_params.json
  blockchain-configs/testnet-dev/node_params.json
  blockchain-configs/testnet-prod/node_params.json
  blockchain-configs/testnet-sandbox/node_params.json
  blockchain-configs/testnet-staging/node_params.json
  client/index.js
  tracker-server/index.js
Labels: enhancement

#888 Add block_timestamp at the highest level in the snapshot for convenience
  common/constants.js
  node/index.js
Labels: enhancement

#887 Support incremental deploy w/ code updates
  deploy_blockchain_genesis_gcp.sh
  deploy_blockchain_incremental_gcp.sh
  deploy_blockchain_sandbox_gcp.sh
  node/index.js
  p2p/index.js
  start_node_genesis_gcp.sh
  start_node_incremental_gcp.sh
Labels: enhancement

#890 Add state bandage feature
  blockchain-configs/base/timer_flags.json
  blockchain-configs/mainnet-prod/timer_flags.json
  blockchain-configs/testnet-prod/timer_flags.json
  common/common-util.js
  common/constants.js
  common/result-code.js
  consensus/index.js
  db/bandage-files/create_app_config_sanitization.js
  db/bandage-files/native_service_path_length_check.js
  db/bandage-files/update_max_state_tree_size_per_byte.js
  db/bandage-files/update_testnet_prod_token_pool_addr.js
  db/functions.js
  db/index.js
  db/rule-util.js
  db/state-util.js
  test/integration/function.test.js
  test/integration/node.test.js
  test/unit/rule-util.test.js
Labels: bug, new feature

#893 Write block file even if another file already exists.
  common/file-util.js
Labels: bug

#895 Feature/liayoo/staking balance total sum
  blockchain-configs/base/timer_flags.json
  blockchain-configs/mainnet-prod/timer_flags.json
  blockchain-configs/testnet-prod/timer_flags.json
  common/constants.js
  common/path-util.js
  db/bandage-files/staking_balance_total_sum.js
  db/functions.js
  db/index.js
  test/integration/function.test.js
  test/integration/node.test.js
  test/test-util.js
  test/unit/consensus.test.js
  test/unit/state-util.test.js
Labels: enhancement

#897 Move rule changes for allow_lower_case_app_names_only flag to a bandage file
  blockchain-configs/1-node/genesis_block.json.gz
  blockchain-configs/2-nodes/genesis_block.json.gz
  blockchain-configs/3-nodes/genesis_block.json.gz
  blockchain-configs/afan-shard/genesis_block.json.gz
  blockchain-configs/base/genesis_block.json.gz
  blockchain-configs/base/genesis_rules.json
  blockchain-configs/base/timer_flags.json
  blockchain-configs/he-shard/genesis_block.json.gz
  blockchain-configs/mainnet-prod/genesis_rules.json
  blockchain-configs/mainnet-prod/timer_flags.json
  blockchain-configs/sim-shard/genesis_block.json.gz
  blockchain-configs/testnet-dev/genesis_block.json.gz
  blockchain-configs/testnet-prod/genesis_rules.json
  blockchain-configs/testnet-prod/timer_flags.json
  blockchain-configs/testnet-sandbox/genesis_block.json.gz
  blockchain-configs/testnet-staging/genesis_block.json.gz
  common/common-util.js
  db/bandage-files/allow_lower_case_app_names_only.js
Labels: enhancement

#896 Improve deployment related code and scripts
  block-pool/index.js
  blockchain/index.js
  common/file-util.js
  consensus/index.js
  deploy_blockchain_genesis_gcp.sh
  deploy_blockchain_incremental_gcp.sh
  deploy_blockchain_sandbox_gcp.sh
  deploy_monitoring_gcp.sh
  node/index.js
  package.json
  setup_monitoring_gcp.sh
  start_node_genesis_gcp.sh
  start_node_incremental_gcp.sh
  start_tracker_genesis_gcp.sh
  start_tracker_incremental_gcp.sh
  test/unit/state-util.test.js
Labels: bug, enhancement

#899 Include timer flags and bandage map in blockchain status
  common/common-util.js
  p2p/index.js
Labels: enhancement

#902 Add blockNumber param to isServAcntName() in bandage files
  db/bandage-files/native_service_path_length_check.js
Labels: bug

#903 Set gas_price = 500 (>= min_gas_price) in the txs of testing tools
  tools/checkin/sendCancelCheckinTx.js
  tools/checkin/sendCloseCheckinTx.js
  tools/checkin/sendOpenCheckinTx.js
  tools/checkout/sendCloseCheckoutTx.js
  tools/checkout/sendOpenCheckoutTx.js
  tools/escrow/sendEscrowConfigTx.js
  tools/escrow/sendHoldTx.js
  tools/escrow/sendReleaseTx.js
  tools/payments/sendClaimTx.js
  tools/payments/sendCreateAppTx.js
  tools/payments/sendPayTx.js
  tools/staking/config_gcp.js
  tools/staking/sendCreateAppTx.js
  tools/staking/sendStakeTx.js
  tools/staking/sendUnstakeTx.js
  tools/transfer/sendTransferTx.js
Labels: bug

#904 Set enabled_block = 42300 for new timer flags of testnet-prod
  blockchain-configs/testnet-prod/timer_flags.json
Labels: release

#905 Set enabled_block = 44600 for new timer flags of MAINNET-prod
  blockchain-configs/mainnet-prod/timer_flags.json
Labels: release

#909 Fix LOG_HEADER undefined issue.
  consensus/index.js
Labels: bug

#910 Merge release v1.0.2 into develop branch
  client/protocol_versions.json
  package.json
Labels: release

#907 Handle mismatched genesis block hash case and null value cases properly
  blockchain-configs/afan-shard/node_params.json
  blockchain-configs/base/node_params.json
  blockchain-configs/he-shard/node_params.json
  blockchain-configs/mainnet-prod/node_params.json
  blockchain-configs/sim-shard/node_params.json
  blockchain-configs/testnet-dev/node_params.json
  blockchain-configs/testnet-prod/node_params.json
  blockchain-configs/testnet-sandbox/node_params.json
  blockchain-configs/testnet-staging/node_params.json
  blockchain/block.js
  consensus/index.js
  node/index.js
  p2p/index.js
  p2p/p2p-util.js
Labels: bug, enhancement

#912 Include timer flag status (enabled, disabled) in /get_config
  common/constants.js
  monitoring/grafana.json
  p2p/index.js
Labels: enhancement

#917 Compute available size by available bytes and replace tree size checks with tree bytes checks
  blockchain-configs/base/timer_flags.json
  blockchain-configs/mainnet-prod/timer_flags.json
  blockchain-configs/testnet-prod/timer_flags.json
  common/result-code.js
  db/bandage-files/update_max_state_tree_size_per_byte2.js
  db/index.js
  node/index.js
  test/integration/node.test.js
Labels: enhancement

#924 Merge release/v1.0.3 into develop branch
  blockchain-configs/mainnet-prod/timer_flags.json
  blockchain-configs/testnet-prod/timer_flags.json
  client/protocol_versions.json
  package.json
Labels: release

#923 Use enabled_block = 2 for additional timer flags in base configs
  blockchain-configs/base/timer_flags.json
Labels: enhancement

#926 Feature/liayoo/update bandwidth budget params
  blockchain-configs/base/timer_flags.json
  blockchain-configs/mainnet-prod/timer_flags.json
  blockchain-configs/testnet-prod/timer_flags.json
  db/bandage-files/update_bandwidth_budget_params.js
Labels: enhancement

#930 Fix bandwidth budget updates not applying
  tx-pool/index.js
Labels: bug
