Repository ainblockchain/ain-blockchain, pull requests merged in 2022-06, with the labels that each got.

#1055 Return child node serial when is_partial = true
  db/radix-tree.js
  db/state-node.js
  test/integration/node.test.js
  test/unit/db.test.js
  test/unit/radix-tree.test.js
  test/unit/state-node.test.js
Labels: enhancement

#1054 Rename: MessageTypes -> P2pMessageTypes
  common/constants.js
  p2p/index.js
  p2p/server.js
Labels: enhancement

#1056 Load json file for topology
  tracker-server/example.json
  tracker-server/index.html
  tracker-server/index.js
Labels: enhancement

#1059 Fix wrong comparison with ipV6
  client/middleware.js
  common/common-util.js
  common/network-util.js
  db/rule-util.js
  p2p/p2p-util.js
  p2p/server.js
  package.json
  test/unit/network-util.test.js
  test/unit/p2p-util.test.js
  test/unit/rule-util.test.js
Labels: bug, enhancement

#1062 Quick fix on some json rpc result returning parts
  json_rpc/admin.js
  p2p/server.js
Labels: bug, enhancement

#1063 Internally separate error from result in get API results
  client/index.js
  common/constants.js
  db/index.js
  json_rpc/database.js
Labels: enhancement

#1065 Merge v1 and v2 get APIs (json rpc APIs and dev client APIs)
  client/index.js
  common/constants.js
  db/index.js
  json_rpc/database.js
  test/integration/node.test.js
Labels: enhancement

#1066 Simplify result format by not using 'error' property
  client/index.js
  common/result-code.js
  common/version-util.js
  db/index.js
  json_rpc/admin.js
  json_rpc/database.js
  json_rpc/transaction.js
  test/integration/blockchain.test.js
  test/integration/node.test.js
Labels: enhancement

#1060 Remove disconnectable peer candidates
  p2p/index.js
  p2p/p2p-util.js
  p2p/server.js
  test/unit/p2p-util.test.js
Labels: enhancement, new feature

#1071 Simplify actions
  .github/workflows/github-actions.yml
Labels: enhancement

#1070 Fix result formats of ain_validateAppName() and ain_checkProtocolVersion()
  common/version-util.js
  db/index.js
  json_rpc/admin.js
  json_rpc/app.js
  json_rpc/transaction.js
  json_rpc/version.js
  test/integration/node.test.js
  test/unit/db.test.js
Labels: enhancement

#1073 Turn on UPDATE_FRONT_DB_OPTION for all nodes
  deploy_blockchain_genesis_gcp.sh
  deploy_blockchain_incremental_gcp.sh
  deploy_blockchain_sandbox_gcp.sh
Labels: bug

#1074 Docker multi-arch build support
  deploy_docker.sh
Labels: enhancement

#1075 Fix broken integration test
  p2p/index.js
  test/integration/sharding.test.js
Labels: bug

#1076 Hotfix integration test
  test/integration/he_sharding.test.js
  test/integration/sharding.test.js
Labels: bug

#1077 Use getTreeMaxSiblings() instead of numChildren() in max siblings limit check
  common/constants.js
  db/index.js
  db/radix-node.js
  db/radix-tree.js
  db/state-node.js
  node/index.js
  test/integration/node.test.js
  test/unit/db.test.js
  test/unit/p2p.test.js
  test/unit/radix-node.test.js
  test/unit/state-node.test.js
  test/unit/state-util.test.js
Labels: bug
